{% set name = "tsoutliers" %}
{% set version = "0.6-10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tsoutliers
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/{{ name }}_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz
  sha256: 0e9e30bcd8861e67201a5e57a915a7e920105d021adbccf35f32ffe0c55e0560

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip  # [win]
  host:
    - r-base
    - r-forecast
  run:
    - r-base
    - r-forecast

test:
  commands:
    - $R -e "library('tsoutliers')"           # [not win]
    - "\"%R%\" -e \"library('tsoutliers')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tsoutliers
  license: GPL-2.0-or-later
  summary: 'Detection of Outliers in Time Series.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - benhuff
    - conda-forge/r
